.github/workflows/docs.yml

fix(ci): point to correct build path

---

CONTRIBUTING.md
README.md
docs/content/_index.md

infra: update instructions

---

docs/quartz.layout.ts

chore(docs): add empty exception file with footer

---

Cargo.toml
ExceptionGranted.md
README.md
crates/morph/Cargo.toml
crates/morph/src/main.rs

chore: add structure for GUI

---

docs/content/Checklists/index.md

docs: update links for checklist in graph view

---

docs/quartz/build.ts
docs/quartz/components/Explorer.tsx
docs/quartz/components/ExplorerNode.tsx

perf: have more than 1ms granularity for rebuild detection
perf: eagerly compute explorer nodes to avoid re-render in memoized value

quartz: update with upstream [eb9bbd1 => 16a9caa]

---

.gitattributes

fix(git): update correct attributes on custom quartz

---

docs/quartz.layout.ts
docs/quartz/plugins/emitters/folderPage.tsx
docs/quartz/plugins/emitters/tagPage.tsx

fix(docs): add correct footer

---

docs/quartz/styles/custom.scss

fix(styling): expand explorer size

---

docs/content/Scratch.md

chore: initialize scratchpad

---

docs/content/.obsidian.vimrc
docs/content/.obsidian/hotkeys.json
docs/quartz.config.ts
docs/quartz.layout.ts
docs/quartz/components/Comments.tsx
docs/quartz/components/ContentMeta.tsx
docs/quartz/components/MinimalFooter.tsx
docs/quartz/components/scripts/comments.inline.ts
docs/quartz/styles/custom.scss

fix(docs): correct comments styling

---

pyproject.toml
python/asteraceae/pyproject.toml
python/asteraceae/src/asteraceae/__init__.py
python/asteraceae/src/asteraceae/bentofile.yaml
python/asteraceae/src/asteraceae/bentovllm_openai/protocol.py
python/asteraceae/src/asteraceae/bentovllm_openai/utils.py
python/asteraceae/src/asteraceae/requirements.txt
python/exo/README.md
python/exo/notebooks/self_explanation.ipynb
python/exo/pyproject.toml
python/exo/src/exo/self_explanation.py
uv.lock

add base server running with vLLM and BentoML

feat(python): add initial SAE experiement

---

.github/workflows/docs.yml
.github/workflows/pr-preview.yml
CONTRIBUTING.md

feat(ci): add preview pages per PR

---

docs/package-lock.json
docs/package.json

fix(deps): update esbuild together

---

docs/content/References.bib
docs/content/Scratch.md
docs/quartz.config.ts
docs/quartz/plugins/transformers/index.ts
docs/quartz/plugins/transformers/twitter.ts
docs/quartz/styles/custom.scss

feat(docs): add embedded twitter

---

docs/quartz/styles/custom.scss

fix(docs): remove extraneous padding

---

docs/content/SRS/SRS.md

chore(docs): use Volere templates

---

.github/dependabot.yml

chore(dependabot): grouped dependencies update per week

---

docs/content/ProblemStatementAndGoals/ProblemStatement.md

docs: adjust problem statement to align with new user group

---

.github/workflows/docs.yml

ci: migrate to pnpm

---

docs/content/SRS/SRS.md

docs(srs): functional requirements

---

docs/content/SRS/SRS.md

Added a detailed reflection section to the SRS document. My reflection covers aspects such as what went well, encountered challenges, insights from user discussions, relevant courses, and the skills and knowledge needed for the project's successful completion. This addition provides insight into my thought process and ongoing learning efforts throughout the capstone project.

docs(srs): add reflection on SRS deliverable process

---

docs/content/HazardAnalysis/HazardAnalysis.md

Introduces an initial draft for several key sections of the Hazard Analysis document, including Definition of Hazard, Critical Assumptions, Safety and Security Requirements, and Roadmap. These sections have been developed to establish a foundational understanding of potential risks, define key security measures, and outline an actionable plan for mitigating hazards. The draft aims to provide a comprehensive approach to address security challenges while ensuring the tinymorph project maintains system integrity and user safety throughout its development.

docs(ha): Assumptions, Safety and Security Requirements, and Roadmap

---

docs/content/HazardAnalysis/HazardAnalysis.md

Added my reflection for the Hazard Analysis deliverable. It includes insights on what went well, challenges faced and resolved, considerations for risks identified, and other potential risks that are important in the context of software products. The reflection aims to document my thought process and learning experiences during the completion of the Hazard Analysis.

docs(ha): Nebras reflection

---

docs/content/VnVPlan/VnVPlan.md

This PR includes the following sections completed:
1. **Tests for Nonfunctional Requirements**:
- Developed a detailed set of test cases covering nonfunctional aspects, such as performance, usability, and security, with clear descriptions, inputs, outputs, and methodologies.
2. **Traceability Between Test Cases and Nonfunctional Requirements**:
- Created a traceability matrix linking each nonfunctional test case to its corresponding requirement, ensuring full traceability and validation.
3. **Modules for Tests for Nonfunctional Requirements**:
- Structured and defined specific modules for nonfunctional testing, including areas such as Inference Engine, User Interface, Deployment Management, and more.
4. **Traceability Between Nonfunctional Test Cases and Modules**:
- Compiled a …

docs(vnv): module, tests and traceability for nonfunctional requirements

---

docs/content/VnVPlan/VnVPlan.md

docs(vnv): functional Tests and traceability matrix

---

docs/content/VnVPlan/VnVPlan.md

Added a reflection for the Verification and Validation (V&V) plan. It details the successes, challenges, required team skills, and strategies for skill development. The reflection aligns with project goals and ensures a cohesive approach to the V&V plan.

docs(vnv): reflection

---

docs/content/VnVPlan/VnVPlan.md

I have replaced all references in the doc to Appendix A with Usability Survey Questions.

docs(vnv): formatting fix

---

docs/content/projMngmnt/POC_Team_Contrib.md

Added documentation for supervisor/stakeholder meeting attendance with Dr. Swati Mishra and TA document discussion attendance. This includes an overview of each team member's participation and context for any absences, emphasizing team commitment and communication.

docs(poc): supervisor/stakeholder meeting attendance and TA document discussion attendance

---

packages/morph/package-lock.json
packages/morph/package.json
packages/morph/postcss.config.js
packages/morph/src/index.css
packages/morph/tailwind.config.js

Integrated TailwindCSS into the project, including:  
- Installing TailwindCSS, PostCSS, and Autoprefixer.  
- Adding configuration files (`tailwind.config.js`, `postcss.config.js`).  
- Importing Tailwind base styles in `src/index.css`.  
- Setting template paths in `tailwind.config.js`.  
This setup enables TailwindCSS for styling.

infra: setup TailwindCSS with configuration and template paths

---

docs/content/Design/MG.md
docs/content/Design/MIS.md
docs/quartz/components/ContentMeta.tsx
docs/quartz/processors/parse.ts

Signed-by: Aaron Pham <contact@aarnphm.xyz>

docs(mis): add initial backend inference specification

---

docs/content/Design/MIS.md

- Fix MIS Styling: Enhanced the formatting for better readability and consistency across documentation.
- Update UI Frontend Modules: Improved editor and notes functionality with refined Markdown previews and interactive features.
- Add Reflections: Documented team contributions, challenges, and design decisions for better project insights.
These changes improve documentation quality, UI functionality, and overall project maintainability.

docs: enhance MIS documentation, update UI modules, and add reflections

---

docs/quartz/components/scripts/popover.inline.ts
docs/quartz/components/scripts/util.ts

fix(docs): only scroll to same hash instead of fetch

---

packages/morph/index.html
packages/morph/src/page/Editor/MarkdownFileUpload.tsx
packages/morph/src/page/Editor/NotesPanel.tsx
packages/morph/src/page/Editor/Setting.tsx
packages/morph/src/page/Editor/Settings.tsx
packages/morph/src/page/Editor/Workspace.tsx

- Adjusted layout for better alignment and spacing.
- Removed the gutter and line numbers for a cleaner appearance.
- Enhanced button functionality with icons for improved usability.
- Applied visual refinements such as hiding the focus outline and optimizing padding.
- Added a basic template for the settings to handle configurations for the editor and page.
These changes improve the user experience and lay the groundwork for customizable settings.

chore(editor): enhance editor UI with layout and button updates

---

packages/morph/src/index.scss
packages/morph/src/page/Editor/Workspace.tsx
packages/morph/src/styles/editor.scss
packages/morph/src/styles/variables.scss

Refactored the styling in the codebase to improve maintainability and consistency. Key changes include:
- Created a `variables.scss` file to centralize and manage all style variables such as fonts, colors, and weights.
- Moved `EditorView.theme` styling from `Workspace.tsx` to `editor.scss` for better separation of concerns.
- Applied additional styling cleanup and restructuring to ensure better modularity.
These updates help standardize styling across the project, allowing for future changes to be easier an efficient to implement.

chore: refactor styling for variables and editor styles

---

packages/morph/package.json
packages/morph/src/components/ui/menubar.tsx
packages/morph/src/page/Editor/MarkdownFileUpload.tsx
packages/morph/src/page/Editor/NotesPanel.tsx
packages/morph/src/page/Editor/Settings.tsx
packages/morph/src/page/Editor/Workspace.tsx
packages/morph/src/styles/editor.scss
pnpm-lock.yaml

Refined the workspace layout by introducing a grid-based structure for better organization and cleaner visuals. Key updates include:
- Integrated a menu bar using Shadcn UI components for consistent design and functionality.  
- Cleaner placement of the editor, menu bar, and notes panel with smoother interactions.  
- Ensured the editor remains left-aligned with proper spacing when the Notes panel is displayed.  
These updates improve the UI’s structure and overall usability, making the screen more concise and polished.

feat(editor): enhanced layout with menu bar and cleaner UI

---

docs/content/VnVPlan/VnVPlan.md

Addressed the issue of accommodating different writing workflows and accessibility needs in the progress tracking features. 
Addresses [Issue #189](https://github.com/aarnphm/morph/issues/189)

docs(mis): improve progress tracking for workflows and accessibility

---

python/asteraceae/requirements.txt
python/asteraceae/service.py

- **feat: perf perf perf reasoning streaming tasks go brrr**
- **feat: disagregated service**

feat(service): disagregated serving

---

packages/morph/app/globals.css
packages/morph/app/page.tsx
packages/morph/app/template.tsx
packages/morph/app/vaults/[vault]/page.tsx
packages/morph/app/vaults/page.tsx
packages/morph/components/editor.tsx
packages/morph/components/landing/page-transition.tsx
packages/morph/components/rails.tsx
python/asteraceae/pyproject.toml

feat: banners research, suggestions highlighting, and more visual cues

---

.gitignore
packages/morph/app/layout.tsx
packages/morph/components/editor.tsx
packages/morph/components/steering-panel.tsx
packages/morph/context/pglite-context.tsx
packages/morph/db.ts
packages/morph/lib/pglite.ts
packages/morph/package.json
pnpm-lock.yaml
python/asteraceae/libs/protocol.py
python/asteraceae/pyproject.toml
python/asteraceae/service.py
uv.lock

feat: embedding matcher
